name: CI

on:
  push:
    branches: [ master ]

jobs:
  explicit-secrets:
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: staging
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  inherited-secrets:
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: production
    secrets: inherit
