name: CI

on:
  push:
    branches: [ master ]

jobs:
  pin-by-tag:
    uses: garion247/shared-workflows/.github/workflows/build.yml@v1.0.0
    with:
      target: staging

  pin-by-branch:
    uses: garion247/shared-workflows/.github/workflows/build.yml@master
    with:
      target: development

  pin-by-sha:
    uses: garion247/shared-workflows/.github/workflows/build.yml@94005b7ca693fd3b23b009955fee3a67353b2558
    with:
      target: production
