name: Version Pins

on:
  push:
    branches: [ master ]

jobs:
  broken-v2-call:
    uses: garion247/shared-workflows/.github/workflows/build.yml@v2
    with:
      target: legacy
      # release-channel is missing - v2 requires it
