name: Version Pins

on:
  push:
    branches: [ master ]

jobs:
  stays-on-v1:
    uses: garion247/shared-workflows/.github/workflows/build.yml@v1
    with:
      target: legacy

  upgraded-to-v2:
    uses: garion247/shared-workflows/.github/workflows/build.yml@v2
    with:
      target: modern
      release-channel: stable
